CMakeLists.txt
README.md
single_include/kompute/Kompute.hpp
src/CMakeLists.txt
src/Tensor.cpp
src/include/kompute/Core.hpp
src/include/kompute/operations/OpAlgoBase.hpp
test/CMakeLists.txt
test/TestLogisticRegression.cpp
test/TestMain.cpp
test/TestManager.cpp
test/TestMultipleAlgoExecutions.cpp
test/TestOpCreateTensor.cpp
test/TestOpShadersFromStringAndFile.cpp
test/TestSequence.cpp
test/TestTensor.cpp
vcpkg.json.opt

Migrating to gtest

---

Makefile
README.md
docs/overview/advanced-examples.rst
docs/overview/reference.rst
single_include/AggregateHeaders.cpp
single_include/kompute/Kompute.hpp
src/OpCreateTensor.cpp
src/OpTensorCopy.cpp
src/OpTensorCreate.cpp
src/OpTensorSyncDevice.cpp
src/OpTensorSyncLocal.cpp
src/Sequence.cpp
src/Tensor.cpp
src/include/kompute/Tensor.hpp
src/include/kompute/operations/OpAlgoBase.hpp
src/include/kompute/operations/OpAlgoLhsRhsOut.hpp
src/include/kompute/operations/OpBase.hpp
src/include/kompute/operations/OpCreateTensor.hpp
src/include/kompute/operations/OpTensorCopy.hpp
src/include/kompute/operations/OpTensorCreate.hpp
src/include/kompute/operations/OpTensorSyncDevice.hpp
src/include/kompute/operations/OpTensorSyncLocal.hpp
test/TestLogisticRegression.cpp
test/TestManager.cpp
test/TestMultipleAlgoExecutions.cpp
test/TestOpShadersFromStringAndFile.cpp
test/TestOpTensorCopy.cpp
test/TestOpTensorCreate.cpp
test/TestOpTensorSync.cpp
test/TestTensor.cpp

Fixes:
* #40 
* #39 
* #42 
* #43 
* #47

Optensor extension

---

README.md
test/TestOpAlgoLoopsPassingData.cpp

Added test that verifies loops function as expected

---

single_include/kompute/Kompute.hpp
src/Manager.cpp
src/Sequence.cpp
src/include/kompute/Manager.hpp
test/TestAsyncOperations.cpp
test/TestLogisticRegression.cpp
test/TestMultipleAlgoExecutions.cpp

74 Fixing manager default sequence creation

---

src/OpTensorCreate.cpp

Added destructor for staging tensors

---

python/src/docstrings.hpp
python/src/main.cpp
single_include/kompute/Kompute.hpp
src/OpAlgoLhsRhsOut.cpp
src/OpTensorCreate.cpp
src/OpTensorSyncDevice.cpp
src/OpTensorSyncLocal.cpp
src/Tensor.cpp
src/include/kompute/Tensor.hpp
src/include/kompute/operations/OpAlgoLhsRhsOut.hpp
src/include/kompute/operations/OpBase.hpp
src/include/kompute/operations/OpTensorCreate.hpp
src/include/kompute/operations/OpTensorSyncDevice.hpp
src/include/kompute/operations/OpTensorSyncLocal.hpp
test/TestLogisticRegression.cpp
test/TestManager.cpp
test/TestOpTensorCopy.cpp
test/TestOpTensorCreate.cpp
test/TestTensor.cpp

Addresses 1st part of #136, and implements new design proposed on #130

Removed Staging Tensors in favour of having two buffer & memory in a Tensor to minimise data transfer

---

Makefile
python/src/docstrings.hpp
python/src/main.cpp
python/test/test_kompute.py
scripts/requirements.txt
single_include/kompute/Kompute.hpp
src/Manager.cpp
src/include/kompute/Manager.hpp
test/TestDestroy.cpp

Closes #36 and builds upon #136 discussion + closing #113 in favour of this.
Outstanding: 
* Add python bindings
* Add documentation

Added destroy functions for tensors and sequences (named and object)

---

.github/workflows/python_tests.yml
python/src/main.cpp
python/test/test_kompute.py

Fixes #147
Required to ensure blog posts still work.

Added temporary backwards compatibility for eval_tensor_create_def function

---

single_include/AggregateHeaders.cpp
single_include/kompute/Kompute.hpp
src/OpAlgoDispatch.cpp
src/OpMemoryBarrier.cpp
src/OpTensorCopy.cpp
src/OpTensorSyncDevice.cpp
src/OpTensorSyncLocal.cpp
src/Tensor.cpp
src/include/kompute/Tensor.hpp
src/include/kompute/operations/OpMemoryBarrier.hpp

Fixes #181
Fixes #45
Relevant to #131

Updated memory barriers to include staging buffers

---

test/TestMultipleAlgoExecutions.cpp

Added memory barrier on test

---

python/test/test_kompute.py

Extending list_devices test to verify more than 0 devices as some will have more than 1

Extending list_devices test for multiple devices

---

python/src/main.cpp

Adding destroy function to manager python bindings

Added destroy for manager

---

test/TestAsyncOperations.cpp
test/TestManager.cpp
test/TestMultipleAlgoExecutions.cpp
test/TestSequence.cpp
test/TestTensor.cpp

Adding tests to util functions to ensure there is broader code coverage

Increase test cov across codebase

---

src/Manager.cpp

Fix for null debug log causing exception in fmt lib

---

README.md

Updated readme to reflect shader utils

---

.github/workflows/cpp_tests.yml
.github/workflows/python_tests.yml
docker-builders/Makefile
docs/index.rst
python/README.md
src/Algorithm.cpp
src/Manager.cpp
src/OpAlgoDispatch.cpp
src/include/kompute/Algorithm.hpp
src/include/kompute/Manager.hpp
test/TestAsyncOperations.cpp
test/TestLogisticRegression.cpp
test/TestManager.cpp
test/TestMultipleAlgoExecutions.cpp
test/TestPushConstant.cpp
test/TestSpecializationConstant.cpp
test/TestTensor.cpp

Updated formatting

---

src/Algorithm.cpp

Signed-off-by: tpoisonooo <khj.application@aliyun.com>

style(src/Algorithm): fix typo

---

README.md
docs/overview/community.rst

Updated discord link

---

CMakeLists.txt

Signed-off-by: tpoisonooo <khj.application@aliyun.com>

fix(CMakeLists.txt): typo

---

.github/workflows/cpp_examples.yml
.github/workflows/cpp_tests.yml
examples/android/android-simple/app/src/main/cpp/CMakeLists.txt
examples/array_multiplication/CMakeLists.txt
examples/array_multiplication/src/main.cpp
examples/logistic_regression/CMakeLists.txt
examples/logistic_regression/shader/my_shader.comp
examples/logistic_regression/src/main.cpp

Fixes #313
Signed-off-by: Alejandro Saucedo <axsauze@gmail.com>

Adding CI setup to ensure examples are tested automatically

---

src/CMakeLists.txt

https://github.com/KomputeProject/kompute/issues/427

feat: Add log library linking to Android build
