examples/array_multiplication/CMakeLists.txt
single_include/kompute/Kompute.hpp
src/include/kompute/Manager.hpp
src/include/kompute/operations/OpAlgoBase.hpp
src/include/kompute/operations/OpAlgoLhsRhsOut.hpp
test/TestManager.cpp

The removal of the references to temporary variables fixed the compilation of the array_multiplication example.
The removal of the default argument of `kp::Manager::evalOp` was necessary to use `kp::Manager::evalOpDefault(std::vector<std::shared_ptr<Tensor>>, const char*)`

Fix compiler errors on compilers other than msvc

---

README.md
docs/conf.py
docs/index.rst
docs/overview/advanced-examples.rst
docs/overview/async-parallel.rst
docs/overview/game-engine-godot.rst
docs/overview/memory-management.rst
docs/overview/mobile-android.rst
docs/overview/reference.rst
docs/overview/shaders-to-headers.rst
examples/android/android-simple/README.md
examples/godot_logistic_regression/README.md
examples/godot_logistic_regression/custom_module/README.md
examples/godot_logistic_regression/gdnative_shared/README.md
single_include/kompute/Kompute.hpp
src/Algorithm.cpp
src/Manager.cpp
src/Sequence.cpp
src/include/kompute/Core.hpp
src/include/kompute/Manager.hpp
src/include/kompute/Sequence.hpp
src/include/kompute/operations/OpAlgoBase.hpp
test/TestAsyncOperations.cpp
test/TestMultipleAlgoExecutions.cpp

Fixes #51 
This PR contains:
* Kompute Manager now can be initialized with multiple queues
* Sequence can now be created with explicitly provided queue
* Evaluation commands can be executed asynchonously with Async/Await
* Contains test that evaluates performance of synchronous vs asynchronous through simple benchmark
* Adds extra documentation on the topic

Adding Asynchronous Processing Capabilities with Multiple Queue Support

---

examples/android/android-simple/app/src/main/cpp/KomputeModelML.cpp
examples/godot_logistic_regression/custom_module/kompute_model_ml/KomputeModelMLNode.cpp
examples/godot_logistic_regression/gdnative_shared/src/KomputeModelML.cpp
examples/logistic_regression/src/Main.cpp
single_include/kompute/Kompute.hpp

77 Fix end to end examples by creating tensors on separate sequence

---

README.md

This prevents new developers, who might not have actually worked with Vulkan (but want to work with Kompute), from having to do the extra step in googling the SDK download page. This reduces friction for potential new developers.

Add link to official Vulkan website to download the SDK

---

README.md
docs/index.rst
docs/overview/advanced-examples.rst
docs/overview/async-parallel.rst
single_include/kompute/Kompute.hpp
src/Manager.cpp
src/include/kompute/Algorithm.hpp
src/include/kompute/Manager.hpp
src/include/kompute/Tensor.hpp
src/include/kompute/operations/OpAlgoBase.hpp
src/include/kompute/operations/OpAlgoLhsRhsOut.hpp
src/include/kompute/operations/OpTensorCopy.hpp

Spelling fixes reported by running codespell over docs and sources.

codespell spelling fixes

---

Makefile

If you enable the `KOMPUTE_OPT_BUILD_SHADERS=1` on cmake, shaders will fail to build, as "/c/VulkanSDK/1.2.141.2/Bin32/glslangValidator.exe" is chosen as the default binary, which in non-existance on native linux. What has been done if it's not windows, it'll check whether it's WSL or native linux and will choose the appropriate binary, "/c/VulkanSDK/1.2.141.2/Bin32/glslangValidator.exe"  for WSL and "/usr/bin/glslangValidator" for Linux.
Gonna be honest, I haven't tested it on windows or WSL, but it should work, hopefully

Fix building shaders on native linux

---

python/src/main.cpp
python/test/requirements-dev.txt
python/test/test_array_multiplication.py
python/test/test_kompute.py

`kp.Tensor.data()` returns a list of floats which is neither convenient nor efficient for further processing. I have added the `.numpy()` method which directly returns a numpy array.

Added numpy() method

---

README.md
python/src/main.cpp
python/test/test_kompute.py

Added string parameters for all `eval_algo_str` methods as described in #93 . I have kept the previous methods that accept lists but I guess they are redundant now? Shall I remove them?

String parameter for eval_algo_str methods in Python

---

README.md

There were some missed semi-colons and `>`s which prevented the Simple and Extended examples from compiling; also, the code was trying to print `std::vector` which is not feasible. I could run the first one successfully, but the Extended example(second one) though compiles successfully, crashes my system when trying to execute `sq->eval();` , so I'm not sure. Hope this fix is useful, as I'm still trying to learn this library.

Fixes for the c++ Simple and Extended examples in readme

---

python/src/main.cpp

- Modified `Tensor.set_data()` to directly accept a numpy array. Previously arrays were implicitly converted to lists which is slow
- Simplified `.numpy()` which also results in a small performance boost

Faster set_data()

---

python/src/main.cpp
python/test/test_kompute.py
src/OpAlgoBase.cpp

- bugfix for custom workgroups in C++ (OpAlgoBase.cpp:28)
- added workgroup argument for` Sequence.record_algo*` + test case
- Merged both `Tensor` constructors and it now also accepts numpy arrays

Workgroups for Python

---

src/Tensor.cpp
src/include/kompute/Tensor.hpp
test/TestOpTensorCreate.cpp

Vulkan specs [disallow zero-sized buffers](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkBufferCreateInfo.html). I've run into segfaults accidentally trying to create some and this was mentioned in #14.
I've added an exception with an error message for easier fault finding. The exception is thrown right before buffer creation because that's where the segfault would happen, but one might consider throwing it already in the constructor.

Disallowing zero sized tensors

---

CMakeLists.txt
Makefile
docs/CMakeLists.txt
docs/index.rst
test/CMakeLists.txt

Closes #145 
Adding support for code coverage reports using `gcov` and `lcov`, as well as adding these to the documentation. 
This can be seen in the docs: https://kompute.cc/codecov/
Outstanding:
* Run codecov on full GPU codebase as currently only the CPU tests are verified given it's running on swiftshader

Adding test code coverage using gcov and lcov

---

docs/CMakeLists.txt
docs/assets/custom.css
docs/assets/gcov.css

Fixes #156 
Adds dark mode by default on docs, includes:
* css overrides for main docs
* custom gcov.css file with dark mode
Does not include:
* Dark mode on raw doxygen docs
<table>
<tr>
<td>
Previous
</td>
<td>
Now
</td>
<tr>
<td width="50%">
</td>
<td>
</td>
</tr>
</table>

Added dark mode on docs

---

test/TestShaderResources.cpp

Created test for ShaderResources.
The tests will pass if the GLSL succeeds/fails compiling the shaders given the situation and resources.

Test for ShaderResources

---

src/Sequence.cpp
src/Tensor.cpp

When a Manager is destroyed, the Manager manually destroys Tensors and Sequences. Then the Tensor and Sequence destructors kick in and want to destroy even more, but there is nothing left to destroy so a warning is issued for every Tensor and Sequence. This is very annoying in interactive Python, esp when having a lot of Tensors.
Also, for anonymous sequences `end()` is called too often and results in another warning.
Added checks to avoid this.

Too many warnings

---

python/src/main.cpp
single_include/kompute/Kompute.hpp
src/Manager.cpp
src/include/kompute/Manager.hpp
test/TestManager.cpp

Added `Manager::getDeviceProperties()` which exposes some device parameters that are relevant for Kompute
```python
devprops = mgr.get_device_properties()
print(devprops)
```
```
Device Name:                   SwiftShader Device (LLVM 10.0.0)
Maximum Workgroup Count:       65535, 65535, 65535
Maximum Workgroup Invocations: 128
Maximum Workgroup Size:        128, 128, 64
Timestamps Supported:          False
```
***
(Single Include header changed more than I want, not sure why.)

Device Properties

---

python/src/main.cpp
python/src/utils.hpp
python/test/test_kompute.py
single_include/kompute/Kompute.hpp
src/CMakeLists.txt
src/Manager.cpp
src/include/kompute/Manager.hpp
test/TestManager.cpp

Fixes #185 
Adds:
* Retrieving physical devices
* Having access to the devices properties
* Python returns dictionary with relevant high level properties
* Added tests in cpp and python
* Fixes issue with CMakelists install interface
* Updates auto to explicit types
In separate PR:
* Allow for listing of devices without creating manager (as static function)
* This will require separating instance creation to static function (and debugCallback)
* Generally having the functions creation vk:: resources as static would be beneficial

Add function to list physical devices

---

CMakeLists.txt

There was in extra comma after `KOMPUTE_OPT_REPO_SUBMODULE_BUILD` , which confused IDEs, such as visual studio.

removed the extra comma after KOMPUTE_OPT_REPO_SUBMODULE_BUILD

---

README.md

Updated Vulkan Komputes version from 0.5.2 to 0.7.0
Updated python version from 3.5-3.8 to 3.5-3.8 (works on python 3.9)
Fixed a syntax error on the C++'s example, and in `tensorOutA->data()` changed `data()` to `vector()`

Updated README and fixed a syntax error on C++'s example

---

src/Manager.cpp

Currently, if there are no Vulkan devices or if they use a physicalDeviceIndex that is not available(meaning that they exceed their device count), one would get a seg fault.
It would be more plausible if one would get an error with an explanation instead.

Raises an error when having no/exceeding vulkan device's limit

---

src/CMakeLists.txt
src/Manager.cpp

The code doesn't compile on Linux i386 if `vkEnumeratePhysicalDevices(*(this->mInstance), &deviceCount, nullptr); ` is used(src/Manager.cpp, line 293; I don't know the issue), using `this->mInstance->enumeratePhysicalDevices(&deviceCount, nullptr);` instead solves the problem.
More info:
```cpp
/project/src/Manager.cpp: In member function ‘void kp::Manager::createDevice(const std::vector<unsigned int>&, uint32_t, const std::vector<std::basic_string<char> >&)’:
/project/src/Manager.cpp:293:32: error: cannot convert ‘std::__shared_ptr_access<vk::Instance, __gnu_cxx::_S_atomic, false, false>::element_type’ {aka ‘vk::Instance’} to ‘VkInstance’ {aka ‘VkInstance_T*’}
293 |     vkEnumeratePhysicalDevices(*(this->mInstance), &deviceCount, nullptr);
| …
```

vkEnumeratePhysicalDevices(*(this->mInstance) ... doesn't work on Linux i386

---

src/Manager.cpp

Apparently, `.data()` in some cases introduced incompatibility #209 , this fixes the problem by removing them
Tested with Vulkan SDK-1.1.82

omitted .data() because it is incompatible with vulkan 1.1.x

---

src/CMakeLists.txt

`$<INSTALL_INTERFACE:single_include>` in `src/CMakeLists.txt` causes CMake to look for a non-existent(#212 ), this PR gets back to the approach that was used before, and also temporarily adding the existent approach to Android because apparently, it faces issues when include directories aren't included explicitly.

Fixed the issue that caused CMake to look for non-existent path after being installed

---

src/CMakeLists.txt

Reverts EthicalML/vulkan-kompute#213

Revert "Fixed the issue that caused CMake to look for non-existent path after being installed"

---

docs/overview/python-package.rst
python/src/main.cpp
python/test/test_tensor_types.py

Take the follwing example
```python
m = kp.Manager()
t = m.tensor([1,2,3])
td = t.data()
del t
td
<invalid memory>
```
Currently if a numpy array is fetched from the tensor, the memory ownership is currently not managed correctly. This PR ensures that the numpy array created incrememnts the refcount of the sharedptr for the Tensor object, to ensure that the numpy array can be checked for validity before it's accessed or modified.
With the update in this PR it can be done as follows:
```python
m = kp.Manager()
t = m.tensor([1,2,3])
td = t.data()
del t
td
assert td.base.is_init() == True # OK
m.destroy() # Frees all memory inside tensors
assert td.base.is_init() == False # Consistent to expected setup
del td # Now this calls tensor destructor as refcount reaches 0
```

[PYTHON] Ensure numpy array increments refcount of tensor to keep valid 

---

setup.py

cc @unexploredtest, @axsaucedo, Superchunk. This should fix #221.
Finding Python for CMake is a known issue. [This PR from PyTorch](https://github.com/pytorch/pytorch/pull/57040/), while not directly related to fixing Python installation issues, shows a tried-and-tested way to help CMake find Python. In particular, the following lines are of interest:
```bash
pycmd_no_exit(_py_inc _exitcode "import sysconfig; print(sysconfig.get_path('include'))")
pycmd_no_exit(_py_lib _exitcode "import sysconfig; print(sysconfig.get_path('stdlib'))")
cmake_python_library = "{}/{}".format(
sysconfig.get_config_var("LIBDIR"),
sysconfig.get_config_var("INSTSONAME"))
cmake_python_include_dir = sysconfig.get_path("include")
```
I opted for the first option, as the second option gave an incorrect directory on …

Set PYTHON_INCLUDE_DIR and PYTHON_LIBRARY during installation

---

docs/overview/build-system.rst

cc @axsaucedo.
This PR adds documentation for:
- #222, which introduced `PYTHON_INCLUDE_DIR` and `PYTHON_LIBRARY`
- #223, which introduced `CMAKE_OSX_ARCHITECTURES`

Add documentation for CMake flags

---

python/src/main.cpp

cc @unexploredtest, @axsaucedo, Superchunk. This should fix #230.
The first instance of segfault occurs with a0f9af9, where
```cpp
// main.cpp
- py::object kp_logger;
+ py::object kp_debug, kp_info, kp_warning, kp_error;
```
I suspect that the "attributes" of the `Logger` class (in this case,
```python
kp_debug    = kp_logger.attr("debug");
kp_info     = kp_logger.attr("info");
kp_warning  = kp_logger.attr("warning");
kp_error    = kp_logger.attr("error");
```
) are cleaned up once when the program terminates and then the static global `py::objects` are cleaned up again, leading to segfault.
In [PyTorch](https://github.com/pytorch/pytorch/blob/924717bf5197e075ec6b586c9c4117f5a4fc272b/torch/csrc/distributed/rpc/python_rpc_handler.cpp#L71-L98), there is a similar idea where they use static …

Set kp_debug, kp_info, kp_warning and kp_error to py::none() when the program terminates.

---

src/Manager.cpp

validExtensions now references data that remains constant for its entire life-time.

Avoid using pointers to temporary copies of desired extensions.

---

src/CMakeLists.txt

CMake considers it an error that the target kompute::kompute references the "single_include" folder which is actually installed to "include".
CMakeLists.txt:-1: error: Imported target "kompute::kompute" includes non-existent path "D:/Downloads/kompute-0.8.0/build/install/single_include" in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include: * The path was deleted, renamed, or moved to another location. * An install or uninstall procedure did not complete successfully. * The installation package was faulty and references files it does not provide.

Remove nonexisting "single_include" from INSTALL_INTERFACE

---

docs/overview/python-examples.rst

Tested with ``kp==0.8.0`` which I think is close enough to master. I only checked the first two examples. I'm slightly less sure about the changes to the second example, especially ``create_sequence("op")``.

Fix first two python examples in the docs

---

docs/overview/shaders-to-headers.rst
examples/array_multiplication/src/Main.cpp
examples/godot_examples/custom_module/kompute_summator/KomputeSummatorNode.cpp
examples/godot_examples/gdnative_shared/src/KomputeSummator.cpp

Updating array_mutiplication example to work correctly

Updating array_mutiplication example to work correctly

---

test/TestDestroy.cpp

This PR fixes this test by first syncing the tensor data to the device. When I run the test suite multiple times on my real hardware, the memory on the device was never initialized, so the test would fail on the first run, then succeed, then fail thereafter.

Fix TestDestroy.TestDestroyTensorSingle

---

CMakeLists.txt
docs/overview/build-system.rst
single_include/kompute/Kompute.hpp
src/include/kompute/Core.hpp
test/TestMain.cpp

Added active log level definitions for kompute

---

src/Algorithm.cpp

The value of `ResultValue<T>` should be accessed explicitly. Implicit access is deprecated.
Fixes the second half of: https://github.com/KomputeProject/kompute/issues/278

Fixed Vulkan deprecation warning

---

src/OpAlgoDispatch.cpp
src/OpMemoryBarrier.cpp

This PR removes `#pragma once` since `.cpp` are generally not supposed to be included anywhere.
Partially resolves #278

Removed '#pragma once' from cpp files

---

single_include/kompute/Kompute.hpp
src/include/kompute/Tensor.hpp

Since fmt 8.0.0 enum classes are not being implicitly converted to int any more.
Refference: https://github.com/fmtlib/fmt/issues/1841
Since I have to use fmt 8.0 and therefore can not use the one provided by Kompute, I defined a format extension for `kp::Tensor::TensorDataTypes` and `kp::Tensor::TensorTypes`.
I'm not too sure if they are required in both classes `Tensor.hpp` and `Kompute.hpp`.
Also let me know if the formatting of the code is fine that way, since I was not able to find any guidelines (e.g. a `.clang-format` file).

Enum class fix for fmt 8.x

---

single_include/kompute/Kompute.hpp
src/Manager.cpp
src/OpAlgoDispatch.cpp
src/OpMemoryBarrier.cpp
src/OpTensorCopy.cpp
src/OpTensorSyncDevice.cpp
src/OpTensorSyncLocal.cpp
src/Sequence.cpp
src/Tensor.cpp
src/include/kompute/Sequence.hpp

In preparation for the build system rewrite where ```-Wall -Wextra -Wpedantic -Werror``` will be set by default, this PR fixes all warnings reported.
I removed
```c++
if (this->mQueueIndex < 0) {
throw std::runtime_error("Kompute Sequence queue index not provided");
}
```
without any replacement since `mQueueIndex` will be always set in the constructor anyway.
Fixes: https://github.com/KomputeProject/kompute/issues/278

Fixed compiler warnings

---

src/Manager.cpp
src/include/kompute/Manager.hpp

In order to debug compute shaders using [RenderDoc](https://renderdoc.org/) and its [in application API](https://renderdoc.org/docs/in_application_api.html), one needs access to the `vk::Instance` object held by the `kp::Manager`. This PR introduces a new getter for retrieving the `std::shared_ptr<vk::Instance>` via the `Manager::getVkInstance()`call.

Added an option to get the current vk instance

---

examples/godot_examples/gdnative_shared/README.md
src/Tensor.cpp
src/include/kompute/Sequence.hpp

I was reading through implementation of Kompute and noticed couple small mistakes that should not effect any functionality.
This minor PR fixes them.

Fixes two mistakes in comments and removes one unused vk::MappedMemoryRange

---

docs/overview/shaders-to-headers.rst
examples/android/android-simple/app/src/main/cpp/CMakeLists.txt
examples/array_multiplication/CMakeLists.txt
examples/logistic_regression/CMakeLists.txt

Updates the CMake `fetch_content` repository and git commit to a official Kompute repo.
As mentioned in #287 this had to be done as a successor of #287 once we knew the actual commit hash after merging.

Updated the fetch_content git repo and commit hash

---

.github/workflows/cpp_tests.yml
.github/workflows/python_tests.yml
docker-builders/KomputeBuilder.Dockerfile
docker-builders/Makefile
docker-builders/Swiftshader.Dockerfile
docker-builders/VulkanSDK.Dockerfile

Fixes  #265
Following from work on #302 focused on updating the build system to use Vulkan 1.3.x. This PR includes:
* Updating builder version to 1.3.212.2
* Ensuring builder uses Built VulkanSDK version
* Reducing size of Swiftshader (2gb->100mb) and VulkanSDK (16gb->2gb) images 
* Ensuring Kompute tests can be run locally using https://github.com/nektos/act
* Upgrade to ubuntu 22.04

Upgrading to Vulkan 1.3

---

src/include/kompute/Tensor.hpp

Steps to reproduce
$git clone https://github.com/KomputeProject/kompute.git $cmake -Bbuild
$cd build
$make
$gcc (SUSE Linux) 12.2.1 20221020 [revision 0aaef83351473e8f4eb774f8f999bbe87a4866d7] Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$lsb_release -a
LSB Version:    n/a
Distributor ID: openSUSE
Description:    openSUSE Tumbleweed
Release:        20221124
Codename:       n/a
Error log
In file included from /home/doof/gitrepo/kompute/src/include/kompute/operations/OpTensorCopy.hpp:6,
from /home/doof/gitrepo/kompute/src/OpTensorCopy.cpp:3:
/home/doof/gitrepo/kompute/src/include/kompute/Tensor.hpp:55:27: error: expected ‘)’ before ‘<’ …

Fixed build error on gcc 12

---

src/Sequence.cpp

Hey, I noticed a performance degradation over time 
when repeatedly calling `Sequence::eval(..)` or `Sequence::evalAsync(..)`.
Both functions first clear the currently recorded operations by calling `Sequence::clear()`, 
then record and actually evaluate the new operation.
The problem is - `Sequence::clear()` never actually clears the operations.
This leads to operations just adding up.
This PR simply adds the missing clear call.
I guess this was just an oversight...
I only noticed this problem only in a compute heavy, long running process.

[performance bug] Fix Sequence::clear()

---

.gitignore
src/CMakeLists.txt
src/include/CMakeLists.txt

Issue https://github.com/KomputeProject/kompute/issues/324 mentioned that installation fails on many platforms because
komputeConfigVersion.cmake is missing. I tried and found out that this issue happens on may platforms, (for example, on Windows11 with msvc and clang16, and on archlinux with gcc13 and clang16).
So I add some lines to generate it, and I believe this will fix https://github.com/KomputeProject/kompute/issues/324 .
Header installation is also fixed. An extra install command in src/include/CMakeLists.txt is removed because it requires non-existing directory src/include/logger, but logger headers are in src/include/kompute/logger. This line is redundant because logger headers are already installed with line 30.
Compatibility mode has been set to `SameMajorVersion`, and all …

Fix cmake install2 (with sign off)

---

.github/workflows/cpp_examples.yml
cmake/set_package_info.cmake

I see 2 example tests in "C++ Test" action failed after merging my PR.
It was caused by `CMAKE_SOURCE_DIR` in file `cmake/set_package_info.cmake` to access readme and license files. It seems ok beacuse they works almost the same as `PROJECT_SOURCE_DIR`, but in example builds `CMAKE_SOURCE_DIR` points to `examples/logistic_regression` , however license and readme files are not located here.
So I replaced `CMAKE_SOURCE_DIR` with `PROJECT_SOURCE_DIR` to fix this.
The `cpp_example` gh action is also changed. 
Before this, cmd line parameter `KOMPUTE_OPT_FROM_SOURCE=ON` doesn't start with a `-D` prefix, so it will be ignored without any warnings and the value of `KOMPUTE_OPT_FROM_SOURCE` is still false. 
As a result, example builds will still access kompute **from the remote master branch** …

Fix example build

---

CMakeLists.txt
Makefile
cmake/code_coverage.cmake
docs/overview/ci-tests.rst
scripts/requirements.txt
test/CMakeLists.txt

The codecov cmake targets were accidentally removed as part of #287 but readding in this PR with further fixes including pinned dependencies.

Readded missing codecov cmake targets

---

src/include/kompute/Tensor.hpp
test/TestOpShadersFromStringAndFile.cpp

Currently it is possible to define custom structs for the Push and Spec constants. This PR provides a custom datatype for tensors to enable structs as provided data, together with an example of the operator overloading required.

Enable custom tensor datatypes with structs

---

src/CMakeLists.txt
src/include/kompute/logger/Logger.hpp

These are just a couple of fixes I found while trying to build with OS installs of some pieces.

Python build fixes

---

docs/overview/shaders-to-headers.rst

We need to include ${kompute_BINARY_DIR}/src/shaders/glsl as this is where ShaderOpMult.hpp is built (included from
include/kompute/operations/OpMult.hpp)

Fix example CMake code for generating headers from GLSL code

---

docs/overview/shaders-to-headers.rst
examples/android/android-simple/app/src/main/cpp/KomputeJniNative.cpp
examples/android/android-simple/app/src/main/cpp/KomputeModelML.cpp
examples/array_multiplication/src/main.cpp
examples/godot_examples/custom_module/kompute_summator/KomputeSummatorNode.cpp
examples/godot_examples/gdnative_shared/src/KomputeSummator.cpp
examples/godot_logistic_regression/custom_module/kompute_model_ml/KomputeModelMLNode.cpp
examples/godot_logistic_regression/gdnative_shared/src/KomputeModelML.cpp
examples/logistic_regression/src/main.cpp
src/Manager.cpp
src/OpTensorCopy.cpp
src/Sequence.cpp
src/Tensor.cpp
src/include/kompute/logger/Logger.hpp
src/logger/Logger.cpp
test/TestOpShadersFromStringAndFile.cpp
test/TestOpTensorCopy.cpp

From Makefile:
for val in "examples single_include src test" ; do find $val -depth -iname *.h -or -iname *.c -or -iname *.hpp -or -iname *.cpp | grep -v "shaders" | xargs clang-format -style=file -i; done

Run clang-format command from Makefile

---

src/Tensor.cpp
src/include/kompute/Manager.hpp
src/include/kompute/Tensor.hpp
test/TestTensor.cpp

Added methods reserve() and constructor for Tensor and TensorT

Issue #925: Added noncopy constructor for Tensor and TensorT

---

src/Tensor.cpp
src/include/kompute/Manager.hpp
src/include/kompute/Tensor.hpp
test/TestOpTensorCopy.cpp
test/TestTensor.cpp

Modify the ReserveData test to test some different ways of creating uninitialised tensors.
Remove the test which tests that the size of an uninitialised tensor is zero, as the tensor does have a size it just has no data.

Add tests for using uninitialised tensors.

---

src/Manager.cpp
src/include/kompute/Manager.hpp

When building with `-DKOMPUTE_OPT_USE_BUILT_IN_FMT=OFF` using `fmt` from vcpkg, I was getting build errors in `Manager.cpp` saying `error: no member named 'join' in namespace 'fmt'`. `join` is defined in `<fmt/ranges.h>` which wasn't included. I'm not sure how kompute can build with the built in fmt. 
Another trivial thing was that the `<set>` and `<unordered_map>` headers were not used in `Manager.hpp` so I moved them to `Manager.cpp`.

fix fmt include in Manager

---

test/TestMultipleAlgoExecutions.cpp

Fixes this validation error:
VUID-vkCmdPipelineBarrier-pBufferMemoryBarriers-02817(ERROR / SPEC): msgNum: -541109872 - Validation Error: [ VUID-vkCmdPipelineBarrier-pBufferMemoryBarriers-02817 ] Object 0: handle = 0x55eb3e5027d0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xdfbf5190 | vkCmdPipelineBarrier(): pBufferMemoryBarriers[0].srcAccessMask (VK_ACCESS_TRANSFER_READ_BIT) is not supported by stage mask (VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT). The Vulkan spec states: For any element of pBufferMemoryBarriers, if its srcQueueFamilyIndex and dstQueueFamilyIndex members are equal, or if its srcQueueFamilyIndex is the queue family index that was used to create the command pool that commandBuffer was allocated from, then its srcAccessMask member must only contain access flags that …

Fix barrier in flag TestMultipleAlgoExecutions::SingleSequenceRecord

---

src/Sequence.cpp

Fixes lots of Vulkan Validation errors.

Enable command buffer reset on the command pool

---

cmake/vulkan_shader_compiler.cmake

If CMake calls vulkan_compile_shader multiple times and the shader directory does not exist in the build directory then add_custom_target will be called multiple times with a target name of build-time-make-directory which is not allowed.
Adding the filename of the input file to target name allows this to work and fixes the build.

Use a unique name for CMake build-time-make-directory

---

src/Image.cpp
src/Memory.cpp
src/Tensor.cpp
src/include/kompute/Image.hpp
src/include/kompute/Memory.hpp
test/TestOpCopyImage.cpp
test/TestOpCopyImageToTensor.cpp
test/TestOpCopyTensor.cpp
test/TestOpCopyTensorToImage.cpp
test/TestOpImageCreate.cpp

This is a new memory type with these Vulkan flags set:
case MemoryTypes::eDeviceAndHost:
return vk::MemoryPropertyFlagBits::eDeviceLocal |
vk::MemoryPropertyFlagBits::eHostVisible |
vk::MemoryPropertyFlagBits::eHostCoherent;
It means that a copy between staging and primary memory is not required because the device memory is also host-visible and host-coherent. This type of memory allocation may not be supported on all platforms/devices, but if they do support it it can improve performance by avoiding an unnecessary copy.

Add support for DeviceAndHost memory

---

src/include/kompute/Tensor.hpp

There is a compile error in MacOS 
'recordCopyFrom' overrides a member function but is not marked 'override'
Signed-off-by: Randy Lee <155058195@qq.com>

Fixed a build error in macos

---

README.md
benchmark/TestBenchmark.cpp
docs/overview/advanced-examples.rst

Updated various C++ documentation examples and TestBenchmark to code that will compile. This largely is updating references of `kp::OpTensorSync{Device,Local}` to `kp::OpSync{Device,Local}` and updating algorithms to use `kp::Memory` instead of `kp::Tensor` as these changes were introduced in #388.
Examples from documentation were tested by copying into a local C++ project setup to use Kompute and compile without any modification to the example code.
TestBenchmark was tested by compiling Kompute with `KOMPUTE_OPT_ENABLE_BENCHMARK="ON"` and ensuring the produced binary runs.

Update Various C++ Documentation Examples to Current Interface

---

CMakeLists.txt

Resolves #368 by updating ``fmtlib`` to the highest possible version without introducing compiling issues.
Anything higher than ``11.0.0`` will require some code rewriting.

Upgraded fmtlib from 8.1.1 to 11.0.0 to get rid of compile warnings

---

docs/overview/custom-operations.rst

Noticed while reading through the documentation.
I've used spell checkers in the CI for other doc projects. Not adding one here, but I suggest tracking that in an issue if desired

fix doc typo

---

src/Algorithm.cpp
src/OpAlgoDispatch.cpp
src/OpCopy.cpp
src/OpMemoryBarrier.cpp
src/OpSyncDevice.cpp
src/OpSyncLocal.cpp
src/Sequence.cpp
src/include/kompute/Algorithm.hpp
src/include/kompute/Sequence.hpp
src/include/kompute/operations/OpAlgoDispatch.hpp
src/include/kompute/operations/OpBase.hpp
src/include/kompute/operations/OpCopy.hpp
src/include/kompute/operations/OpMemoryBarrier.hpp
src/include/kompute/operations/OpMult.hpp
src/include/kompute/operations/OpSyncDevice.hpp
src/include/kompute/operations/OpSyncLocal.hpp

In this PR, I add noexcept to all constructors that are noexcept

Add noexcept to all constructors to explicitly state no exception thrown #44

---

src/include/kompute/Algorithm.hpp
src/include/kompute/Image.hpp
src/include/kompute/Manager.hpp
src/include/kompute/Memory.hpp
src/include/kompute/Sequence.hpp
src/include/kompute/Tensor.hpp
src/include/kompute/operations/OpAlgoDispatch.hpp
src/include/kompute/operations/OpBase.hpp
src/include/kompute/operations/OpCopy.hpp
src/include/kompute/operations/OpMemoryBarrier.hpp
src/include/kompute/operations/OpMult.hpp
src/include/kompute/operations/OpSyncDevice.hpp
src/include/kompute/operations/OpSyncLocal.hpp

This is a little different from what described in Issue #20, but I made all the classes in Kompute non-copy. I did not create the NonCopiable class, however the impossibility to copy the classes comes from each class: this is because I do not want to create a class without a purpose other than making the language behave as we want, and because it would not make the copy/assignment operators un-overridable, so it would be possible to do some terrible things and enable the copy on them.

Remove copy operations from classes in Kompute

---

.github/workflows/cpp_tests.yml
src/Manager.cpp
src/include/kompute/Manager.hpp

Fixes https://github.com/KomputeProject/kompute/issues/414

414 support for 1 4 headers

---

src/Manager.cpp

Change VKAPI_PTR to VKAPI_ATTR
Tested only on:
MSVC version: `Microsoft (R) C/C++ Optimizing Compiler Version 19.43.34808 for x86`
VulkanSDK version: 1.4.309.0
Latest kompute commit: 299b11fb4b8a7607c5d2c27e2735f26b06ae8e29

Fix syntax error (MSVC) in Manager.cpp

---

CMakeLists.txt
src/CMakeLists.txt

- Updated CMake to support the latest NDK which no longer includes Vulkan by default.
- Users now need to download [Vulkan SDK](https://vulkan.lunarg.com) and manually set VULKAN_INCLUDE_DIR, for example:
```
set(VULKAN_INCLUDE_DIR /path/to/VulkanSDK/1.3.296.0/macOS/include)
```
- Modified the condition for linking Vulkan-Headers: Now it only links when not building for Android.

Fix compile error in android

---

examples/python_naive_matmul/imp1_naive.py
examples/python_naive_matmul/imp2_tiled.py
examples/python_naive_matmul/imp3_better_tiling.py
examples/python_naive_matmul/utils.py

Updates the Python Matmul examples to support external GLSL compiler via a utility file.
Fixes issue https://github.com/KomputeProject/kompute/issues/433

Update Python Matmul examples
